name: Test MongoDB

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm ci

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0

    - name: Run tests
      run: npm test
